## Project Description: Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [1]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import  pandas as pd

## load the dataset
data=gutenberg.raw('shakespeare-hamlet.txt')
## save to a file
with open('hamlet.txt','w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\goura\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [2]:
## Data Preprocessing

import numpy as np
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##load the dataset
with open('hamlet.txt','r') as file:
    text=file.read().lower()

# Clean text consistently for training and inference
text = re.sub(r'[^a-z0-9\s]', ' ', text)
text = ' '.join(text.split())

## Tokenize the text and create indexes for words
max_words = 2500
tokenizer = Tokenizer(num_words=max_words, oov_token=None)
tokenizer.fit_on_texts([text])
total_words = max_words
total_words



2500

In [3]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'to': 4,
 'of': 5,
 'i': 6,
 'you': 7,
 'a': 8,
 'my': 9,
 'it': 10,
 'in': 11,
 'that': 12,
 'ham': 13,
 'is': 14,
 'not': 15,
 'his': 16,
 'this': 17,
 'with': 18,
 'your': 19,
 'but': 20,
 'for': 21,
 'me': 22,
 'd': 23,
 'what': 24,
 'lord': 25,
 'as': 26,
 'he': 27,
 'be': 28,
 'so': 29,
 'haue': 30,
 'him': 31,
 'king': 32,
 'will': 33,
 'no': 34,
 'on': 35,
 'our': 36,
 'we': 37,
 's': 38,
 'are': 39,
 'if': 40,
 'all': 41,
 'then': 42,
 'by': 43,
 'thou': 44,
 'shall': 45,
 'come': 46,
 'do': 47,
 'let': 48,
 'or': 49,
 'hamlet': 50,
 'good': 51,
 'hor': 52,
 'her': 53,
 'there': 54,
 'now': 55,
 't': 56,
 'thy': 57,
 'they': 58,
 'how': 59,
 'more': 60,
 'from': 61,
 'enter': 62,
 'was': 63,
 'at': 64,
 'oh': 65,
 'like': 66,
 'most': 67,
 'would': 68,
 'well': 69,
 'know': 70,
 'tis': 71,
 'selfe': 72,
 'them': 73,
 'o': 74,
 'loue': 75,
 'may': 76,
 'vs': 77,
 'did': 78,
 'th': 79,
 'sir': 80,
 'qu': 81,
 'too': 82,
 'which': 83,
 'why': 8

In [4]:
## create input sequences
input_sequences=[]
token_list = tokenizer.texts_to_sequences([text])[0]
sequence_length = 25
for i in range(1, len(token_list)):
    start = max(0, i - sequence_length + 1)
    n_gram_sequence = token_list[start:i+1]
    input_sequences.append(n_gram_sequence)



In [5]:
input_sequences

[[2, 687],
 [2, 687, 5],
 [2, 687, 5, 50],
 [2, 687, 5, 50, 43],
 [2, 687, 5, 50, 43, 1854],
 [2, 687, 5, 50, 43, 1854, 1855],
 [2, 687, 5, 50, 43, 1854, 1855, 1856],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175, 1857],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175, 1857, 1858],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175, 1857, 1858, 1859],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175, 1857, 1858, 1859, 62],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175, 1857, 1858, 1859, 62, 408],
 [2, 687, 5, 50, 43, 1854, 1855, 1856, 1175, 1857, 1858, 1859, 62, 408, 3],
 [2,
  687,
  5,
  50,
  43,
  1854,
  1855,
  1856,
  1175,
  1857,
  1858,
  1859,
  62,
  408,
  3,
  1176],
 [2,
  687,
  5,
  50,
  43,
  1854,
  1855,
  1856,
  1175,
  1857,
  1858,
  1859,
  62,
  408,
  3,
  1176,
  185],
 [2,
  687,
  5,
  50,
  43,
  1854,
  1855,
  1856,
  1175,
  1857,
  1858,
  1859,
  62,
  408,
  3,
  1176,
  185,
  1860],
 [2,
  687,
  5,
  50,
  43,
  1854,
 

In [6]:
## Pad Sequences
max_sequence_len = max(len(x) for x in input_sequences)
max_sequence_len

25

In [7]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    2,  687],
       [   0,    0,    0, ...,    2,  687,    5],
       [   0,    0,    0, ...,  687,    5,   50],
       ...,
       [ 120,    1,  109, ...,    5,   50, 1043],
       [   1,  109,  498, ...,   50, 1043,    5],
       [ 109,  498,    2, ..., 1043,    5,  203]])

In [8]:
##create predicitors and label
import tensorflow as tf
x, y = input_sequences[:, :-1], input_sequences[:, -1]

In [9]:
x

array([[   0,    0,    0, ...,    0,    0,    2],
       [   0,    0,    0, ...,    0,    2,  687],
       [   0,    0,    0, ...,    2,  687,    5],
       ...,
       [ 120,    1,  109, ...,  687,    5,   50],
       [   1,  109,  498, ...,    5,   50, 1043],
       [ 109,  498,    2, ...,   50, 1043,    5]])

In [10]:
y

array([ 687,    5,   50, ..., 1043,    5,  203])

In [11]:
# Use sparse labels instead of one-hot encoding for the large output vocabulary
y

array([ 687,    5,   50, ..., 1043,    5,  203])

In [12]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, shuffle=True)

In [13]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [14]:
## LSTM model block disabled. Using GRU only for final training.
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU
#
# ## Define the model
# model=Sequential()
# model.add(Embedding(total_words,128,input_length=max_sequence_len-1,mask_zero=True))
# model.add(LSTM(150,return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(100))
# model.add(Dense(total_words,activation="softmax"))
#
# # #Compile the model
# model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
# model.summary()

In [15]:
## GRU RNN
## Define the model
model=Sequential()
model.add(Embedding(total_words,256,input_length=max_sequence_len-1,mask_zero=True))
model.add(GRU(256,return_sequences=True,dropout=0.3,recurrent_dropout=0.2))
model.add(Dropout(0.3))
model.add(GRU(256))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 24, 256)           640000    
                                                                 
 gru (GRU)                   (None, 24, 256)           394752    
                                                                 
 dropout (Dropout)           (None, 24, 256)           0         
                                                                 
 gru_1 (GRU)                 (None, 256)               394752    
                                                                 
 dense (Dense)               (None, 2500)              642500    
                                                                 
Total params: 2072004 (7.90 MB)
Trainable params: 2072004 (7.90 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
## Train the model
history=model.fit(x_train, y_train, epochs=150, batch_size=64, validation_data=(x_test, y_test), verbose=1, callbacks=[early_stopping])


Epoch 1/150
379/379 [==============================] - 84s 208ms/step - loss: 6.3075 - accuracy: 0.0696 - val_loss: 6.1644 - val_accuracy: 0.0748
Epoch 2/150
379/379 [==============================] - 80s 210ms/step - loss: 6.0650 - accuracy: 0.0711 - val_loss: 6.1265 - val_accuracy: 0.0748
Epoch 3/150
379/379 [==============================] - 76s 200ms/step - loss: 5.8923 - accuracy: 0.0726 - val_loss: 5.9965 - val_accuracy: 0.0750
Epoch 4/150
379/379 [==============================] - 74s 195ms/step - loss: 5.7262 - accuracy: 0.0783 - val_loss: 5.9653 - val_accuracy: 0.0778
Epoch 5/150
379/379 [==============================] - 73s 193ms/step - loss: 5.5747 - accuracy: 0.0888 - val_loss: 5.9222 - val_accuracy: 0.0884
Epoch 6/150
379/379 [==============================] - 74s 196ms/step - loss: 5.3684 - accuracy: 0.1027 - val_loss: 5.9046 - val_accuracy: 0.0945
Epoch 7/150
379/379 [==============================] - 74s 195ms/step - loss: 5.1523 - accuracy: 0.1125 - val_loss: 5.9054 -

In [17]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    return ' '.join(text.split())

def predict_top_k_next_words(model, tokenizer, text, max_sequence_len, k=3):
    text = clean_text(text)
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) == 0:
        return []
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)[0]
    top_k_indices = np.argsort(predicted)[-k:][::-1]
    words = []
    for idx in top_k_indices:
        idx_int = int(idx)
        if idx_int <= 1:
            continue
        word = tokenizer.index_word.get(idx_int)
        if word and word != '<OOV>':
            words.append(word)
    return words

# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    top_words = predict_top_k_next_words(model, tokenizer, text, max_sequence_len, k=3)
    return top_words[0] if top_words else None


In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 24, 256)           640000    
                                                                 
 gru (GRU)                   (None, 24, 256)           394752    
                                                                 
 dropout (Dropout)           (None, 24, 256)           0         
                                                                 
 gru_1 (GRU)                 (None, 256)               394752    
                                                                 
 dense (Dense)               (None, 2500)              642500    
                                                                 
Total params: 2072004 (7.90 MB)
Trainable params: 2072004 (7.90 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:<OOV>


In [ ]:
## Save the model
model.save("next_word_lstm.h5")
## Save the tokenizer
import pickle
# Ensure the saved tokenizer does not retain OOV token behavior
tokenizer.oov_token = None
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

c:\Users\goura\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [21]:
input_text="Tis now strook twelue, get thee to the"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word Prediction:{next_word}")

Input text:Tis now strook twelue, get thee to the
Next Word Prediction:<OOV>
